IF OBJECT_ID ('usp_PS_DOC_HDR_insert') IS NOT NULL
	DROP PROCEDURE [dbo].usp_PS_DOC_HDR_insert
GO

CREATE PROCEDURE [dbo].usp_PS_DOC_HDR_insert
(
	@DOC_ID	BIGINT,
	@STR_ID VARCHAR(10),
	@STA_ID VARCHAR(10),
	@DRW_ID VARCHAR(10),
	@DRW_SESSION_ID BIGINT,
	@TKT_NO VARCHAR(15),
	@DOC_TYP VARCHAR(1),
	@CUST_NO VARCHAR(15),
	@LINS INT,
	@LIN_TOT DECIMAL(15, 2),
	@TAX_COD VARCHAR(10),
	@CUST_PO_NO VARCHAR(20),
	@SLS_REP VARCHAR(10),
	@STK_LOC_ID VARCHAR(10),
	@PRC_LOC_ID VARCHAR(10),
	@PFT_CTR VARCHAR(20),
	@VOID_USR_ID VARCHAR(10),
	@VOID_REAS VARCHAR(10),
	@TAX_EXEMPT_NO VARCHAR(30),
	@TAX_OVRD_REAS VARCHAR(10),
	@DOC_GUID UNIQUEIDENTIFIER,
	@BILL_TO_CONTACT_ID TINYINT,
	@SHIP_TO_CONTACT_ID TINYINT,
	@SHIP_DAT DATETIME,
	@ERR_REF VARCHAR(255),
	@TKT_DT DATETIME,
	@NORM_TAX_COD VARCHAR(10),
	@REF VARCHAR(50),
	@LST_MAINT_DT DATETIME,
	@LST_MAINT_USR_ID VARCHAR(10)
)
AS
/*********************************************************************************
*	Revision History
*
*	Name: 
*	Description: 
*
*	Date:				Author:		Ref#:		Comments:
*	February 12, 2024	RMarinas	N/A			Created.
*
**********************************************************************************/

INSERT INTO dbo.PS_DOC_HDR
(
	DOC_ID,
	STR_ID,
	STA_ID,
	DRW_ID,
	DRW_SESSION_ID,
	TKT_NO,
	DOC_TYP,
	CUST_NO,
	LINS,
	LIN_TOT,
	TAX_COD,
	CUST_PO_NO,
	SLS_REP,
	STK_LOC_ID,
	PRC_LOC_ID,
	PFT_CTR,
	VOID_USR_ID,
	VOID_REAS,
	TAX_EXEMPT_NO,
	TAX_OVRD_REAS,
	DOC_GUID,
	BILL_TO_CONTACT_ID,
	SHIP_TO_CONTACT_ID,
	SHIP_DAT,
	ERR_REF,
	TKT_DT,
	NORM_TAX_COD,
	REF,
	LST_MAINT_DT,
	LST_MAINT_USR_ID
)
VALUES
(
	@DOC_ID,
	@STR_ID,
	@STA_ID,
	@DRW_ID,
	@DRW_SESSION_ID,
	@TKT_NO,
	@DOC_TYP,
	@CUST_NO,
	@LINS,
	@LIN_TOT,
	@TAX_COD,
	@CUST_PO_NO,
	@SLS_REP,
	@STK_LOC_ID,
	@PRC_LOC_ID,
	@PFT_CTR,
	@VOID_USR_ID,
	@VOID_REAS,
	@TAX_EXEMPT_NO,
	@TAX_OVRD_REAS,
	@DOC_GUID,
	@BILL_TO_CONTACT_ID,
	@SHIP_TO_CONTACT_ID,
	@SHIP_DAT,
	@ERR_REF,
	@TKT_DT,
	@NORM_TAX_COD,
	@REF,
	@LST_MAINT_DT,
	@LST_MAINT_USR_ID
)